apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
      metadata:
        name: frontend-pod
        namespace: chat-app
        labels:
          app: frontend
      spec:
        containers:
        - name: chatapp-frontend
          image: etheral829/chat-frontend
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
          - name: NODE_ENV
            value: production  
